### ISSUE TITLE
Share in the community

### ISSUE THREAD

**Issue by Phosphorus-M** [sirfredrick231/VivaldiColorChanger#9]
I'm very impressed for this project. Share the git in the forum, maybe the people will be contribute.
Great f*ckin job dude, this is soo good.

**Comment by sirfredrick** [comment]
I've already shared it [here](https://forum.vivaldi.net/topic/31684/vivaldi-color-changer-service) and [here](https://sirfredrick.vivaldi.net/2018/10/26/vivaldi-color-changer-service/). If you would like to help, I've been thinking about using [RGB.NET](https://github.com/DarthAffe/RGB.NET) to have as wide a compatibility as possible. I have also been working behind the scenes on a way to change Windows and Linux KDE Plasma Themes to the current tab color.
